package com.es.product.search.index;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.elasticsearch.annotations.*;

import java.util.UUID;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(indexName = "products")
@JsonIgnoreProperties(ignoreUnknown = true)
@Setting(settingPath = "/elasticsearch/product-settings.json")
public class ProductIndex {

    @Id
    private UUID id;  // String id, can be UUID or generated by ES

    @Field(type = FieldType.Text, analyzer = "ngram_analyzer", searchAnalyzer = "autocomplete_search")
    private String name;

    @Field(type = FieldType.Text)
    private String sku;

    private String imageUrl;

    @Field(type = FieldType.Text)
    private String description;

    @Field(type = FieldType.Float)
    private float rating;

    @Field(type = FieldType.Double)
    private double price;

    @Field(type = FieldType.Object)
    private Brand brand;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Brand {
        @Field(type = FieldType.Keyword)
        private String id;

        @Field(type = FieldType.Keyword)
        private String name;
    }
}
